# Site settings
title: Dan Belling, Software Developer
description: Hello, Internet.
google_analytics: UA-80211904-1

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
